name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT }}
  SERVICE: ${{ secrets.GCP_SERVICE_NAME }}
  REGION: ${{ secrets.GCP_LOCATION }}

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Go lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest

  sec:
    name: gosec
    needs: lint
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - uses: actions/checkout@v2
      - name: Run Gosec Security scanner
        uses: securego/gosec@master
        with:
          args: ./...

  test:
    needs: sec
    strategy:
      matrix:
        go-version: [1.16.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        run: go test -v ./...

  #     - name: Deploy to Cloud Run
  #       id: deploy
  #       uses: google-github-actions/deploy-cloudrun@v0.4.0
  #       with:
  #         service: ${{ env.SERVICE }}
  #         image: gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:${{  github.sha }}
  #         region: ${{ env.REGION }}

  #     - name: Show Output
  #       run: echo ${{ steps.deploy.outputs.url }}

  deploy:
    name: "Deploy"
    runs-on: ubuntu-latest
    needs: sec
    steps:
      - uses: actions/checkout@v2

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
          export_default_credentials: true

      - name: Authorize Docker push
        run: gcloud auth configure-docker

      - name: Build and Push Container
        run: |-
          docker build -t gcr.io/${{ secrets.GCP_PROJECT }}/${{ secrets.GCP_SERVICE_NAME }}:latest .
          docker push gcr.io/${{ secrets.GCP_PROJECT }}/${{ secrets.GCP_SERVICE_NAME }}:latest

      - name: Deploy to Cloud Run
        id: deploy
        run: |-
          gcloud run deploy ${{ secrets.GCP_SERVICE_NAME }} --image gcr.io/${{ secrets.GCP_PROJECT }}/${{ secrets.GCP_SERVICE_NAME }}:latest --region ${{ secrets.GCP_LOCATION }} --allow-unauthenticated
          yes | gcloud beta run services add-iam-policy-binding ${{ secrets.GCP_SERVICE_NAME }} --member=allUsers --role=roles/run.invoker --region=${{ secrets.GCP_LOCATION }}

      - name: Show Output
        run: echo ${{ steps.deploy.outputs.url }}
