name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  #   build:
  #     runs-on: ubuntu-latest
  #     steps:
  #     - uses: actions/checkout@v2

  #     - name: Set up Go
  #       uses: actions/setup-go@v2
  #       with:
  #         go-version: 1.16

  #     - name: Build
  #       run: go build -v ./...

  #     - name: Test
  #       run: go test -v ./...

  lint:
    name: lint
    runs-on: ubuntu-latest
    # env:
    #   GO111MODULE: on
    steps:
      - uses: actions/checkout@v2
      # - name: Run Go lint
      #   uses: golangci/golangci-lint-action@v2
      #   with:
      #     version: latest
      #     working-directory: app
      - name: Run Gosec Security Scanner
        uses: naokikimura/gosec-action@v0
        with:
          working_directory: app

  # test:
  #   needs: lint
  #   strategy:
  #     matrix:
  #       go-version: [1.16.x]
  #       os: [ubuntu-latest, macos-latest, windows-latest]
  #   runs-on: ${{ matrix.os }}
  #   steps:
  #     - name: Install Go
  #       uses: actions/setup-go@v2
  #       with:
  #         go-version: ${{ matrix.go-version }}
  #     - name: Checkout code
  #       uses: actions/checkout@v2
  #     - name: Test
  #       run: cd app && go test -v ./...
